import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Head from 'next/head';

const merriweather = localFont({
  src: "./fonts/Merriweather-Regular.woff",
  variable: "--font-merriweather",
  weight: "100 900",
});
const poppinSans = localFont({
  src: "./fonts/Poppins-Regular.woff",
  variable: "--font-poppins-sans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "AE Travelia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="../public/assets/favicon.ico" />
      </Head>
      <body
        className={` ${poppinSans.variable} antialiased`}
      >
        <main className="grow">
          {children}
        </main>
      </body>
    </html>
  );
}
